version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=quiz_user
      - DB_PASSWORD=quiz_password
      - DB_NAME=quizz_db
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=quizz_db
      - MYSQL_USER=quiz_user
      - MYSQL_PASSWORD=quiz_password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge