services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=quiz_admin
      - DB_PASSWORD=Quiz123Admin!
      - DB_NAME=quiz_db
      - JWT_SECRET=quiz_jwt_secret_key_2024
      - NODE_ENV=production
      - PORT=5000
      - HOST=stomtest.nsmu.ru
    depends_on:
      - mariadb
    networks:
      - app-network
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    environment:
      - MARIADB_ROOT_PASSWORD=Quiz123Root!
      - MARIADB_DATABASE=quiz_db
      - MARIADB_USER=quiz_admin
      - MARIADB_PASSWORD=Quiz123Admin!
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
