services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://stomtest.nsmu.ru:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=quizz_db
      - DB_USER=quizz_user
      - DB_PASSWORD=quizz_password123
      - NODE_ENV=development
      - PORT=5000
      - HOST=stomtest.nsmu.ru
    restart: always
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules

  mariadb:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=quizz_db
      - MYSQL_USER=quizz_user
      - MYSQL_PASSWORD=quizz_password123
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data: