services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    environment:
      - VITE_API_URL=http://stomtest.nsmu.ru:5000
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=quiz_user
      - DB_PASSWORD=quiz_password
      - DB_NAME=quizz_db
    networks:
      - app-network

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quizz_db
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge