services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://stomtest.nsmu.ru/api
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=quiz_user
      - DB_PASSWORD=quiz_password
      - DB_NAME=quiz_db
      - JWT_SECRET=stomtest-quiz-secret-key-2024
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=quiz_db
      - MYSQL_USER=quiz_user
      - MYSQL_PASSWORD=quiz_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "quiz_user", "--password=quiz_password"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge