services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://stomtest.nsmu.ru:5000
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=quizz_db
      - DB_USER=quizz_user
      - DB_PASSWORD=quizz_password123
      - NODE_ENV=production
      - PORT=5000
      - HOST=stomtest.nsmu.ru
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  mariadb:
    image: mariadb:10.5-focal
    platform: linux/amd64
    command: --max_allowed_packet=128M --sql_mode="NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: quizz_db
      MYSQL_USER: quizz_user
      MYSQL_PASSWORD: quizz_password123
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local

networks:
  app-network:
    driver: bridge