version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5173"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=quiz_admin
      - DB_PASSWORD=Quiz123Admin!
      - DB_NAME=quiz_db
      - JWT_SECRET=quiz_jwt_secret_key_2024
      - HOST=stomtest.nsmu.ru
      - PORT=5000
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=Quiz123Root!
      - MYSQL_DATABASE=quiz_db
      - MYSQL_USER=quiz_admin
      - MYSQL_PASSWORD=Quiz123Admin!
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
