services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    environment:
      - VITE_API_URL=http://stomtest.nsmu.ru:5000
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=quiz_user
      - DB_PASSWORD=quiz_password
      - DB_NAME=quizz_db
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quizz_db
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_password
    volumes:
      - type: bind
        source: ./backend/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge